### ISSUE TITLE
PatchModuleTest_PlatformModPatchModule_0 fails on AIX 

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-systemtest#202]
PatchModuleTest_PlatformModPatchModule_0 and PatchModuleImageTest_PlatformModPatchModule_0 fails on AIX with following error: 

```
OT11 1) testOverrideUsingUpgradablePlatformModule(net.adoptopenjdk.test.modularity.junit.TestOverrideUsingUpgradablePlatformModule)
OT11 java.lang.NoSuchMethodError: javax/xml/namespace/QName.getLocalPart()Ljava/lang/String; (loaded from /home/u0020236/workspace/Test-sanity.system-JDK11-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-override/java.xml by <Bootstrap Loader>) called from class net.adoptopenjdk.test.modularity.junit.TestOverrideUsingUpgradablePlatformModule (loaded from file:/home/u0020236/workspace/Test-sanity.system-JDK11-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test/ by jdk.internal.loader.ClassLoaders$AppClassLoader@be201e87).
OT11 	at com.test/net.adoptopenjdk.test.modularity.junit.TestOverrideUsingUpgradablePlatformModule.testOverrideUsingUpgradablePlatformModule(TestOverrideUsingUpgradablePlatformModule.java:32)
OT11 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
OT11 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
OT11 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OT11 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
OT11 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
OT11 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
OT11 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
OT11 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
OT11 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
OT11 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
OT11 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
OT11 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
OT11 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
OT11 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
OT11 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
OT11 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
OT11 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
OT11 	at org.junit.runners.Suite.runChild(Suite.java:128)
OT11 	at org.junit.runners.Suite.runChild(Suite.java:27)
OT11 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
OT11 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
OT11 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
OT11 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
OT11 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
OT11 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
OT11 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
OT11 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
OT11 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
OT11 	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

**Comment by lumpfish** [comment]
These test targets have had their names shortened - they are now `PatMod_PlatMod_0` and `PatModImg_PlatMod_0`.

**Comment by lumpfish** [comment]
The tests now run OK:

jdk11:
openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8014/console
hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8015/console
jdk16:
openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8016/console
hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8017/console
jdk17:
openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8018/console
hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8022/console

PR to reinstate: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2411

**Comment by lumpfish** [comment]
The tests are now passing on the AdoptOpenJDK nightly builds, closing,
