### ISSUE TITLE
Java 17 jlink fails on Mac OS X Aarch64 due to incorrect architecture

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-systemtest#463]
Java 17 jlink fails on Mac OS X Aarch64 due to incorrect architecture
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk17_hs_sanity.system_aarch64_mac/26/

```
T2 stderr Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/jenkins/workspace/Test_openjdk17_hs_sanity.system_aarch64_mac/aqa-tests/TKG/output_16316650461897/Jlink_ReqMod_0/20210914-182055-JlinkTest/tmp/19.CRI2/lib/libJniTest.dylib: dlopen(/Users/jenkins/workspace/Test_openjdk17_hs_sanity.system_aarch64_mac/aqa-tests/TKG/output_16316650461897/Jlink_ReqMod_0/20210914-182055-JlinkTest/tmp/19.CRI2/lib/libJniTest.dylib, 1): no suitable image found. Did find:
T2 stderr /Users/jenkins/workspace/Test_openjdk17_hs_sanity.system_aarch64_mac/aqa-tests/TKG/output_16316650461897/Jlink_ReqMod_0/20210914-182055-JlinkTest/tmp/19.CRI2/lib/libJniTest.dylib: mach-o, but wrong architecture
T2 stderr /Users/jenkins/workspace/Test_openjdk17_hs_sanity.system_aarch64_mac/aqa-tests/TKG/output_16316650461897/Jlink_ReqMod_0/20210914-182055-JlinkTest/tmp/19.CRI2/lib/libJniTest.dylib: mach-o, but wrong architecture
T2 stderr at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
T2 stderr at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
T2 stderr at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
```

https://github.com/adoptium/aqa-tests/issues/2854

**Comment by sophia-guo** [comment]
Duplicate of #464
