### ISSUE TITLE
OAuthTest failed on all platforms since added.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-systemtest#474]
OAuthTest failed on all platforms since added on Nove 9th. 

The last successful build on Nov 7th. https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.system_x86-64_windows/

```
09:21:35  STF 22:21:34.913 - |
09:21:35  STF 22:21:34.913 - Monitoring processes: CLI
09:21:35  CLI log in YES!
09:21:35  CLI 8889
09:21:36  CLI stderr Exception in thread "main" java.lang.RuntimeException: unexpected result
09:21:36  CLI stderr 	at net.adoptopenjdk.test.auth.Client.main(Client.java:66)
09:21:36  STF 22:21:36.434 - **FAILED** Process CLI ended with exit code (1) and not the expected exit code/s (0)
09:21:36  STF 22:21:36.434 - Monitoring Report Summary:
09:21:36  STF 22:21:36.434 -   o Process CLI ended with exit code (1) and not the expected exit code/s (0)
09:21:36  STF 22:21:36.434 - Killing processes: AUTH CLI SER
09:21:36  STF 22:21:36.434 -   o Process CLI pid 30296 is not running
09:21:36  STF 22:21:36.434 -   o Process AUTH pid 13152 stop()
09:21:36  STF 22:21:36.435 -   o Process AUTH pid 13152 killed
09:21:36  AUTH stderr java.io.IOException: headers already sent
09:21:36  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:206)
09:21:36  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:85)
09:21:36  AUTH stderr 	at net.adoptopenjdk.test.auth.AuthCenter$ProtectedResourceHandler.handle(AuthCenter.java:133)
09:21:36  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
09:21:36  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
09:21:36  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
09:21:36  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:728)
09:21:36  AUTH stderr 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
09:21:36  AUTH stderr 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:695)
09:21:36  AUTH stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
09:21:36  AUTH stderr 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
09:21:36  AUTH stderr 	at java.base/java.lang.Thread.run(Thread.java:833)
09:21:36  STF 22:21:36.435 -   o Process SER pid 13708 stop()
09:21:36  STF 22:21:36.436 -   o Process SER pid 13708 killed
```

@joeyleeeeeee97 could you take a look at this?

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/issues/3223#issuecomment-1015602055

**Comment by smlambert** [comment]
Also failing on sparcv9_solaris jdk8 (see https://github.com/adoptium/aqa-tests/issues/4518#issuecomment-1516315745).
