### ISSUE TITLE
Mauve incompatibility with java

### ISSUE THREAD

**Issue by emankhalaf** [adoptium/aqa-systemtest#484]
Hi,

when I run mauve from command line, I got this error:

[warning] /usr/bin/mauve: No JAVA_CMD set for run_java, falling back to JAVA_CMD = java
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "."
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.gel.mauve.gui.Mauve.hasRequiredJVM(Unknown Source)
	at org.gel.mauve.gui.Mauve.init(Unknown Source)
	at org.gel.mauve.gui.Mauve$2.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

java version installed on my machine is :+1: openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)

I found a suggestion for a previously posted issue to use older version of java
https://www.biostars.org/p/9498908/#9541541

but I am not sure whether this will conflict with the already installed version?
Any suggestions, please?

**Comment by karianna** [comment]
@emankhalaf Mave does not support Java 10+ so you will need to install our1.8.0_362 release.
